CREATE TABLE IF NOT EXISTS beyond_wallet (
    uid     TEXT NOT NULL REFERENCES beyond_players(uid) ON DELETE CASCADE PRIMARY KEY,
    gold    INTEGER NOT NULL DEFAULT 9999999,
    diamond INTEGER NOT NULL DEFAULT 9999999
);
